<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classes-upload [
    <!ELEMENT classes-upload (classes)>
    <!ATTLIST classes-upload operation (insert|update) "insert">
    <!ELEMENT classes (class+)>
    <!ELEMENT class (id?, name, description, duration,dates, timeslot, location, trainers )>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT duration (#PCDATA)>
    <!ELEMENT dates (#PCDATA)>
    <!ELEMENT timeslot (#PCDATA)>
    <!ELEMENT location (building,room)>
    <!ELEMENT building (#PCDATA)>
    <!ELEMENT room (#PCDATA)>
    <!ELEMENT trainers (trainer+)>
    <!ELEMENT trainer (#PCDATA)>
]>

<classes-upload operation="insert">
    <classes>
        <class>
            <name>Pilates Class</name>
            <description>A low-impact workout that focuses on strength, flexibility, and balance.</description>
            <duration>45</duration>
            <dates>2023-03-11T13:00:00.000+00:00</dates>
            <timeslot>1:00 PM - 1:45 PM</timeslot>
            <location>
                <building>XYZ Gym</building>
                <room>Pilates Studio</room>
            </location>
            <trainers>
                <trainer>Emily Johnson</trainer>
            </trainers>
        </class>
            </classes>
</classes-upload>


<classes-upload operation="update">
    <classes>
        <class>
            <name>Pilates Class</name>
            <description>A low-impact workout that focuses on strength, flexibility, and balance.</description>
            <duration>45</duration>
            <dates>2023-03-11T13:00:00.000+00:00</dates>
            <timeslot>1:00 PM - 1:45 PM</timeslot>
            <location>
                <building>XYZ Gym</building>
                <room>Pilates Studio</room>
            </location>
            <trainers>
                <trainer>Emily Johnson</trainer>
            </trainers>
        </class>
            </classes>
</classes-upload>